# Generated by Django 6.1.1 on 2026-09-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clients/')),
                ('temoignage', models.TextField(blank=True)),
                ('lien', models.URLField(blank=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Collaboration',
                'verbose_name_plural': 'Collaborations',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(blank=True, max_length=150)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message reçu',
                'verbose_name_plural': 'Messages reçus',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(default='Lazaki Chelsoube', max_length=100)),
                ('titre', models.CharField(default='Étudiant en Licence 2 Génie Logiciel · Développeur Full-Stack', max_length=150)),
                ('bio', models.TextField(default="Développeur Full-Stack / Software Engineer. J'aime transformer des besoins en architectures propres, bien structurées et évolutives.")),
                ('processus_travail', models.TextField(blank=True, default="Je pars toujours du besoin réel avant le code : je clarifie les objectifs, je découpe le problème en modules simples, puis j'avance par itérations courtes et testées.", help_text='Comment vous travaillez : méthode, outils, étapes.')),
                ('email', models.EmailField(default='tresorchelsoube@gmail.com', max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('github', models.URLField(blank=True, default='https://github.com/lazakichelsoube-prog/')),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True, default='https://www.instagram.com/top_tresor/')),
                ('behance', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('cv', models.FileField(blank=True, help_text='CV en PDF (optionnel)', null=True, upload_to='cv/')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('technologies', models.CharField(help_text='Liste séparée par des virgules, ex : Django, JavaScript, PostgreSQL', max_length=200)),
                ('lien_demo', models.URLField(blank=True)),
                ('lien_code', models.URLField(blank=True, help_text='Lien vers le dépôt GitHub')),
                ('en_vedette', models.BooleanField(default=True, help_text='Afficher ce projet sur le site')),
                ('date_realisation', models.DateField(blank=True, null=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Réalisation',
                'verbose_name_plural': 'Réalisations',
                'ordering': ['ordre', '-date_realisation'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('categorie', models.CharField(choices=[('dev', 'Développement'), ('reseau', 'Réseau & Systèmes'), ('outil', 'Outils & Autres')], default='dev', max_length=10)),
                ('niveau', models.PositiveSmallIntegerField(default=70, help_text='Niveau de maîtrise de 0 à 100 (affiché comme barre de progression).')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage (plus petit = en premier).")),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['categorie', 'ordre', 'nom'],
            },
        ),
    ]
