# Generated by Django 6.1.1 on 2026-09-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_donnees_initiales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(help_text="Ex : '2025 — Aujourd'hui', '2024 — 2025', 'En continu'", max_length=60)),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage (plus petit = affiché en premier).")),
            ],
            options={
                'verbose_name': 'Étape du parcours',
                'verbose_name_plural': 'Parcours',
                'ordering': ['ordre'],
            },
        ),
        migrations.AlterField(
            model_name='skill',
            name='niveau',
            field=models.PositiveSmallIntegerField(default=70, help_text='Niveau de maîtrise de 0 à 100.'),
        ),
    ]
